#builder
FROM golang:1.24-alpine AS builder

WORKDIR /app

# Copy go mod/sum files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build go
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./main.go

# service
FROM alpine:3.21

WORKDIR /app

# Copy the binary from the builder stage
COPY --from=builder /app/server .

# Expose port 5000
EXPOSE 5000

# Run the server
CMD ["./server"]